Fixes issues when testing game availability via provided file.
libretro/scummvm pull request #15
Opened 2023-02-06 19:41 UTC by Gemba

- Fix: `*.scummvm` file with valid game short name but heading/trailing whitespace is not recognized.
- Fix: Test if provided file is directory (if file has not extension `.scummvm`) and provide corrected directory to scummvm engine. Works now also with relative paths.
- Enh: Parameter `game_id` set to `const char *` in `retroTestGame()` as in other functions of that module.
- Enh: Log messages on how the game was successfully identified or failed to be identified.

2023-02-07 00:35 UTC, spleen1981 requested changes

2023-02-07 00:35 UTC, spleen1981 commented on src/libretro.cpp
> +				detect_dir = detect_dir.getParent();
You can use the `parent_dir` defined with `Common::FSNode` previously.

2023-02-07 00:35 UTC, spleen1981 commented on src/libretro.cpp
> -		char *gamedir = dirname(path);
As `Common::FSNode` is introduced, better to stick with it and be consistent:

- direct use of `path` and `game->path` should be removed and replaced with `Common::FSNode detect_target` - definition and assignment to be moved here.

- parent folder can be defined here e.g. as `Common::FSNode parent_dir`, resolved and reused it later as needed.

2023-02-07 00:35 UTC, spleen1981 commented on src/libretro.cpp
> +		Common::FSNode detect_dir;
better name would be `detect_target` to avoid confusion, and should be moved up, ref prev comment

2023-02-07 00:35 UTC, spleen1981 commented on src/libretro.cpp
> +			detect_dir = Common::FSNode(game->path);
move outside this block, ref prev comment

2023-02-08 16:31 UTC, Gemba commented on src/libretro.cpp
> +			strcpy(filedata, trimmed);
common/str.h from ScummVM provides a trim(). I used that.

2023-02-08 16:32 UTC, Gemba commented on src/libretro.cpp
> +#include <regex>
Ok. No longer needed.

2023-02-08 16:32 UTC, Gemba commented on src/libretro.cpp
> +				sprintf(buffer, "-p \"%s\" %s", gamedir, filedata);
Changed to `parent_dir` and `detect_target` as recommended.

2023-02-08 16:33 UTC, Gemba commented on src/libretro.cpp
> +			detect_dir = Common::FSNode(game->path);
Moved to head of function.

2023-02-08 16:37 UTC, Gemba commented on src/libretro.cpp
> +				if (detect_dir.getName().equals(detect_dir.getParent().getName())) {
Re: Your question: If there is no directory provided then FSNode returns a clone of the current node.
Second part is applied.

2023-02-08 21:20 UTC, spleen1981 approved these changes

2023-02-08 21:20 UTC, merged